### ISSUE TITLE
remove all references to visibility:collapse

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#563] opened 2015-08-07 12:25 UTC
`visibility:collapse` is not supported by gecko yet (at least for non-table elements), and we use it like `display:none` in some places. Let's get rid of that.

**Comment by Gozala** [comment] 2015-08-07 23:52
This is duplicate of #495 that has more details.

**Comment by paulrouget** [comment] 2015-08-08 07:30
No, there are reference to `collapse` in other places.

**Closed** 2015-08-11 00:46 UTC
