### ISSUE TITLE
Graphene does not autoupdate

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#375] opened 2015-05-15 23:03 UTC
Looking at about:settings I see `deviceinfo.platform_build_id: 20150505044202` which looks like it's 15 days behind.

**Comment by Gozala** [comment] 2015-05-18 22:44
So it looks like runtime still isn't updating given that today I'm on `20150515044201` instead of `20150518.....`

**Comment by gordonbrander** [comment] 2015-05-18 22:53
Same here. `deviceinfo.platform_build_id: 20150505044202`

**Comment by paulrouget** [comment] 2015-05-19 00:45
Download the latest nightly, and please tell me if it updates once we get a new build.

**Comment by gordonbrander** [comment] 2015-05-19 18:20
@paulrouget same problem, even after updating to yesterday's build.

**Comment by gordonbrander** [comment] 2015-05-19 18:20
@Gozala is this a dupe of https://github.com/mozilla/browser.html/issues/379?

**Comment by paulrouget** [comment] 2015-05-20 06:41
> @Gozala is this a dupe of #379?

No, it's about the app, not graphene. We have 2 update mechanisms, and they are apparently both broken.

**Comment by paulrouget** [comment] 2015-05-21 11:03
I can confirm:

With: http://ftp.mozilla.org/pub/mozilla.org/b2g/nightly/2015-05-18-04-42-05-larch/
Knowing that there's a build for the day after: http://ftp.mozilla.org/pub/mozilla.org/b2g/nightly/2015-05-19-04-42-07-larch/
… with mar files.

update.xml is empty: https://aus4.mozilla.org/update/3/Graphene/41.0a1/20150518044205/Darwin_x86_64-gcc3/en-US/default/Darwin%2014.4.0/default/default/update.xml?force=1

Logs:
```
*** AUS:SVC Checker: checkForUpdates, force: true
*** AUS:SVC getLocale - getting locale from file: resource://app/update.locale, locale: en-US
*** AUS:SVC Checker:getUpdateURL - update URL: https://aus4.mozilla.org/update/3/Graphene/41.0a1/20150518044205/Darwin_x86_64-gcc3/en-US/default/Darwin%2014.4.0/default/default/update.xml?force=1
*** AUS:SVC gCanCheckForUpdates - able to check for updates
*** AUS:SVC Checker:checkForUpdates - sending request to: https://aus4.mozilla.org/update/3/Graphene/41.0a1/20150518044205/Darwin_x86_64-gcc3/en-US/default/Darwin%2014.4.0/default/default/update.xml?force=1
XXX FIXME : Got a mozContentEvent: force-update-check
*** AUS:SVC Checker:onLoad - request completed downloading document
*** AUS:SVC Checker:onLoad - number of updates available: 0
*** AUS:SVC UpdateManager:_loadXMLFileIntoArray: XML file does not exist
```

**Comment by paulrouget** [comment] 2015-05-21 11:03
Filed bug https://bugzilla.mozilla.org/show_bug.cgi?id=1167150

**Comment by paulrouget** [comment] 2015-05-25 02:56
Fixed.

**Closed by paulrouget** 2015-05-25 02:56 UTC
Labels: graphene, regression
