### ISSUE TITLE
Clicking close button on tabs sometimes doesn't work

### ISSUE THREAD

**Issue by nt1m** [mozilla/browser.html#849] opened 2016-01-24 23:14 UTC
It's very hard since the hit area is very small.

**Comment by gordonbrander** [comment] 2016-01-25 17:12
Will investigate. Could be a bug with Servo's hit targets? The hit target of the close button should cover the whole height of the tab and be fairly wide as well.

**Comment by gordonbrander** [comment] 2016-01-25 19:42
Confirmed: the hit target works as expected in Gecko, but in Servo is difficult to click, or sometimes does not trigger.

**Comment by gordonbrander** [comment] 2016-01-25 19:46
Wait! There is another bug with clicking the close tab button when you only have one tab left. This is present in Gecko and Servo.

**Comment by gordonbrander** [comment] 2016-01-25 20:00
Hmm, actually this seems to happen in Gecko as well. It doesn't have anything to do with the hit target. Individual tabs sometimes get "stuck" somehow and don't react to being closed with `x`. However, you can still use `cmd w`. The problem is sporadic. Maybe a state bug?

Here's a video of it not working https://gfycat.com/OptimisticSerpentineArrowana.

cc @Gozala

**Comment by nt1m** [comment] 2016-01-25 20:09
@gordonbrander Yeah, the screencast shows quite well what I was experiencing on Gecko.

**Comment by gordonbrander** [comment] 2016-01-25 21:40
I think this might be a race between `sidebar-tab` triggering `mousedown` and the close button triggering `click`.

**Comment by gordonbrander** [comment] 2016-01-25 21:52
Confirmed: this is a `click` vs `mousedown` race condition.

**Comment by gordonbrander** [comment] 2016-01-25 21:59
Furthermore, `cmd w` will close the current tab and select the next tab. The close button does not do this properly. We need to make sure the same actions are sent through for both.

**Comment by gordonbrander** [comment] 2016-01-25 23:51
There are several problems happening here:

- Race between `mousedown` and `click` events in tab view
- Figuring out why we have to send both `Select` and `Activate` from tab. Only `Select` seems to do anything but `Activate` is really the thing we should be sending, and it should do a `select`.
- The difference between `cmd w` and close button handling. The former correctly activates the adjacent tab when closing a tab, the latter does not.

**Comment by gordonbrander** [comment] 2016-01-26 00:13
@Gozala do you know why we only select the adjacent tab when closing active webview? https://github.com/mozilla/browser.html/blob/master/src/browser/web-views.js#L341

**Comment by Gozala** [comment] 2016-01-26 00:28
> @Gozala do you know why we only select the adjacent tab when closing active webview? https://github.com/mozilla/browser.html/blob/master/src/browser/web-views.js#L341

Because if closed tab isn't active we don't need to adjust anything ?

**Comment by Gozala** [comment] 2016-01-26 00:31
@gordonbrander BTW this line should no longer be necessary, it was a hack we had to do before some of the stuff got fixed, but I guess I forgot to remove it.
https://github.com/mozilla/browser.html/blob/master/src/browser/sidebar/tab.js#L183

That being said it's still odd that it causes this bug, it should not I would like to find out why is it causing this bug if it really is the reason.

**Comment by gordonbrander** [comment] 2016-01-26 00:32
@Gozala the strange thing is https://github.com/mozilla/browser.html/blob/master/src/browser/sidebar/tab.js#L183 `Select` is the action that works. `Activate` seems to do nothing.

**Comment by Gozala** [comment] 2016-01-26 02:14
Here is an overview of what was going on:

1. We had a `onMouseDown` event listener on tab which triggered SelectTabByID action, causing active tab to be deselected and clicked tab to be selected.
2. Tab close button's `onClick` event listener was triggering `CloseTabByID` action.
3. Perspective UI code would trigger hid tabs animation when `SelectTabByID` action was triggered.
4. Since `onMouseDown` was triggered prior to `onClick` and it was starting `HideTabs` animation `onClick` sometimes would not fire since DOM element would move. Which is why `CloseTabByID` was not triggered either & causing malfunction.

My pull request removes `SelectTabByID` and all the wiring associated with it. It also fixes logic in perspective-ui module to trigger `HideTabs` animation on tab activation instead of selection as tab selection is removed and in fact that makes more sense anyhow.

**Comment by Gozala** [comment] 2016-01-26 02:16
Unfortunately my changes introduce a regression it tab switching code on `ctrl tab` not entirely sure why, I suspect there was more stuff related to tab selection than I thought.

**Closed** 2016-01-26 02:18 UTC
Labels: interaction
