### ISSUE TITLE
Typing in the locationbar resizes the result box making it jumpy

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#627] opened 2015-08-22 00:33 UTC
STR:

1. type "mo"
2. see top result + 3 search + 3 historic results
3. add a "z"
4. for a short time, see top result + 3 search + 2 historic results
5. see top result + 3 search + 3 historic results
6. add a new character, go to (4)

Because of (3), the box keeps being resized as you type, making the effect very jumpy.

**Comment by Gozala** [comment] 2015-09-03 05:47
@gordonbrander any suggestions how to mitigate that UX vice ?

**Comment by gordonbrander** [comment] 2015-09-03 15:47
This is a dupe of https://github.com/mozilla/browser.html/issues/623. When we solve timing issues with results, this should be much less of an issue.

**Comment by gordonbrander** [comment] 2015-12-10 22:58
This bug is out-of-date. (Does not apply to current codebase).

**Closed by gordonbrander** 2015-12-10 22:58 UTC
