### ISSUE TITLE
Tile loading doesn't handle redirects properly

### ISSUE THREAD

**Issue by PalmerAL** [mozilla/browser.html#235] opened 2015-03-12 21:17 UTC
go to "mail.google.com" -> premade tile loads
go to "gmail.com" (redirects to mail.google.com) -> premade tile does not load

**Comment by paulrouget** [comment] 2015-03-14 09:18
Dupe of #97

**Comment by PalmerAL** [comment] 2015-03-14 14:56
I'm not sure this is the same thing. In this case, you are redirected to mail.google.com, which should then match the mail.google.com tile. This isn't related to domain matching.

**Comment by paulrouget** [comment] 2015-03-15 01:32
Oh right. I read that wrong.

**Comment by Gozala** [comment] 2015-04-23 05:09
This was fixed by this change https://github.com/mozilla/browser.html/commit/05932a6cdad9954a6c2d355d92e6889877848313#diff-ac64a61ab532164b9e3f853bfb7ee2d7R111 issue was that tile was fetched from `iframe.src` which was no longer a loaction of the page.

**Closed by Gozala** 2015-04-23 05:09 UTC
Labels: ugly
