### ISSUE TITLE
Window.open/close seems to be missing reference

### ISSUE THREAD

**Issue by KevinGrandon** [mozilla/browser.html#398] opened 2015-06-12 03:35 UTC
Test case: http://jsfiddle.net/p907Ld4v/5/

It seems that window.open and the handler to close that window aren't fully supported yet. This works on b2g, so maybe it's just a matter of hooking into the mozbrowser event somehow?

**Comment by KevinGrandon** [comment] 2015-06-16 22:35
I think I may have this fixed actually for my case. I think you just need to use the iframe element from the mozbrowseropenwindow detail, instead of constructing a frame. I might be able to submit a PR, but I'm still not too familiar with the browser.html guts.

**Comment by Gozala** [comment] 2015-08-07 19:00
This is dupe of #475

**Closed by Gozala** 2015-08-07 19:00 UTC
