### ISSUE TITLE
Cards don't look good for github issues

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#610] opened 2015-08-19 10:06 UTC
We see the avatar of the reporter as a hero image, but this has nothing to do with the issue or even github.

<img width="1092" alt="screen shot 2015-08-19 at 12 05 11" src="https://cloud.githubusercontent.com/assets/373579/9353696/9a9c4410-466a-11e5-9e93-42354687459a.png">

**Comment by gordonbrander** [comment] 2015-08-20 18:39
This has been bugging me too. Unfortunately, Github chose to set the avatar as `<meta name="twitter:image">` and `<meta property="og:image">`.

No easy fix for this one. In the short term, we could create a blacklist, kind of like we do for colors.

**Comment by gordonbrander** [comment] 2015-08-20 18:44
We could also get smart and try to identify "types" of pages by looking for patterns in classnames, etc.

**Comment by Gozala** [comment] 2015-09-03 05:50
@gordonbrander @paulrouget for what it worth, safari does similar thing 

<img width="493" alt="screen shot 2015-09-02 at 10 49 36 pm" src="https://cloud.githubusercontent.com/assets/21236/9651391/eb122ab2-51c4-11e5-83c9-7d7d7d209980.png">

I also don't find it to be that bad, although in our case text in the card definitely could be better.

**Comment by gordonbrander** [comment] 2015-09-03 14:51
Dupe of https://github.com/mozilla/browser.html/issues/652

**Closed by gordonbrander** 2015-09-03 14:51 UTC
Labels: effort: XL, reward: XL
