### ISSUE TITLE
Session restore breaks often

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#486] opened 2015-07-14 17:42 UTC
This seems to happen most often when refreshing on the dashboard:

- Load page
- Navigate to card dashboard
- Hit `fn f5`
- Session is not restored!

...but not always. Sometimes we fail to restore even when viewing a page.

See also https://github.com/mozilla/browser.html/issues/476#issuecomment-121112262

**Comment by Gozala** [comment] 2015-08-05 02:15
I have figured out the issue which is relate to selection state, when we select all we set selection to `{start: 0, end: Infinity}` but `JSON.serialize({start: 0, end: Infinity})` produces `{start:0, end:null}` which causes invalid state to be stored for the session.

The for this issue is one liner that I've included in the different pull:
https://github.com/mozilla/browser.html/pull/547/files#diff-2c8b4521eac83629c3dc939a131e56f7R229

I can cherry-pick it to land separately.

**Comment by Gozala** [comment] 2015-08-05 02:21
@gordonbrander wanna look at the pull and see if resolves the issue, also note that this was regression introduced during refactoring that also breaks test selection in the input which is also fixed by this change. Basically when we update selection by setting it to `{start: 0, end: Infinity}` that causes `selection` event that should contain actual integer `end` value that is then stored into state there for we avoid bug caused by `JSON.serialize` outlined above.

**Closed** 2015-08-05 19:04 UTC
