### ISSUE TITLE
Window is always created with gap at top

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#118] opened 2015-02-19 22:24 UTC
I notice the window is consistently created in a position where there is a gap that is exactly the size of a standard window title bar. This may be a runner bug, not a browser.html bug. cc @paulrouget

**Comment by paulrouget** [comment] 2015-02-20 04:22
Right. And we need to implement size, position and mode persistence. This is a Gecko bug.

**Comment by paulrouget** [comment] 2015-03-12 10:12
Dupe of #176

**Closed by paulrouget** 2015-03-12 10:12 UTC
